import { Process } from './types'

const today = new Date()
const daysAgo = (days: number) => {
  const d = new Date(today)
  d.setDate(d.getDate() - days)
  return d.toISOString().split('T')[0]
}

export const mockProcesses: Process[] = [
  {
    id: 'DEV-1001',
    type: 'Devolução Comum',
    customer: 'Auto Peças Silva',
    product: 'Filtro de Ar',
    sku: 'FA-100',
    supplier: 'Filtros S/A',
    seller: 'João Pedro',
    requestDate: daysAgo(5),
    value: 150.0,
    status: 'Pendente de Análise',
    slaDays: 5,
    category: 'Outros',
    purchaseDate: daysAgo(20),
    invoiceNumber: 'NF-12345',
    returnReason: '1 - Comprei errado',
    returnDescription: 'Comprei o filtro para o modelo antigo do carro.',
  },
  {
    id: 'GRT-1002',
    type: 'Garantia',
    customer: 'Oficina do Marcos',
    product: 'Amortecedor Dianteiro',
    sku: 'AM-200',
    supplier: 'Monroe',
    seller: 'Ana',
    requestDate: daysAgo(400), // > 365 days (Excedido)
    value: 450.0,
    status: 'Pendente de Análise',
    slaDays: 400,
    category: 'Amortecedor',
    purchaseDate: daysAgo(450),
    invoiceNumber: 'NF-54321',
    applicationDate: daysAgo(440),
    applicationKm: 12000,
    defectDate: daysAgo(410),
    defectKm: 25000,
    defectDescription: 'Vazamento de óleo prematuro na peça esquerda.',
  },
  {
    id: 'GRT-1003',
    type: 'Garantia',
    customer: 'Centro Automotivo RJ',
    product: 'Pastilha de Freio',
    sku: 'PF-300',
    supplier: 'Bosch',
    seller: 'Carlos',
    requestDate: daysAgo(100), // > 90 days (Excedido)
    value: 120.0,
    status: 'Nota Fiscal em Análise',
    returnInvoiceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slaDays: 100,
    category: 'Outros',
  },
  {
    id: 'DEV-1004',
    type: 'Devolução Comum',
    customer: 'Mecânica Express',
    product: 'Correia Dentada',
    sku: 'CD-400',
    supplier: 'Gates',
    seller: 'Ana',
    requestDate: daysAgo(10), // > 7 days (Excedido)
    value: 85.0,
    status: 'Conferência de Estoque',
    slaDays: 10,
    category: 'Outros',
  },
  {
    id: 'GRT-1005',
    type: 'Garantia',
    customer: 'Auto Peças Silva',
    product: "Bomba d'água",
    sku: 'BD-500',
    supplier: 'Urba',
    seller: 'João Pedro',
    requestDate: daysAgo(50),
    value: 320.0,
    status: 'Aguardando Créditos',
    supplierCreditReceived: false,
    customerCreditReleased: true,
    slaDays: 50,
    category: 'Outros',
  },
  {
    id: 'DEV-1006',
    type: 'Devolução Comum',
    customer: 'Oficina do Marcos',
    product: 'Vela de Ignição',
    sku: 'VI-600',
    supplier: 'NGK',
    seller: 'Carlos',
    requestDate: daysAgo(2),
    value: 60.0,
    status: 'Crédito Recusado',
    creditDecisionReason: 'Peça apresenta sinais de uso incorreto, impossibilitando revenda.',
    slaDays: 2,
    category: 'Outros',
  },
  {
    id: 'GRT-1007',
    type: 'Garantia',
    customer: 'Centro Automotivo RJ',
    product: 'Amortecedor Traseiro',
    sku: 'AM-201',
    supplier: 'Monroe',
    seller: 'Ana',
    requestDate: daysAgo(10),
    value: 450.0,
    status: 'Autorizado emissão da nota fiscal',
    slaDays: 10,
    category: 'Amortecedor',
  },
]

export const generateId = () => `PRC-${Math.floor(Math.random() * 10000) + 2000}`
