import { Process } from './types'

export const mockProcesses: Process[] = [
  {
    id: 'DEV-1001',
    type: 'Devolução Comum',
    customer: 'Auto Peças Silva',
    product: 'Filtro de Ar',
    sku: 'FA-100',
    supplier: 'Filtros S/A',
    seller: 'João Pedro',
    requestDate: '2023-10-01',
    value: 150.0,
    status: 'Pendente de Análise',
    slaDays: 2,
    category: 'Outros',
    purchaseDate: '2023-09-25',
    invoiceNumber: 'NF-12345',
    returnReason: '1 - Comprei errado',
    returnDescription: 'Comprei o filtro para o modelo antigo do carro.',
  },
  {
    id: 'GRT-1002',
    type: 'Garantia',
    customer: 'Oficina do Marcos',
    product: 'Amortecedor Dianteiro',
    sku: 'AM-200',
    supplier: 'Monroe',
    seller: 'Ana',
    requestDate: '2023-09-15',
    value: 450.0,
    status: 'Produto Recebido',
    slaDays: 18,
    category: 'Amortecedor',
    purchaseDate: '2023-01-10',
    invoiceNumber: 'NF-54321',
    applicationDate: '2023-01-15',
    applicationKm: 12000,
    defectDate: '2023-09-10',
    defectKm: 25000,
    defectDescription: 'Vazamento de óleo prematuro na peça esquerda.',
  },
  {
    id: 'GRT-1003',
    type: 'Garantia',
    customer: 'Centro Automotivo RJ',
    product: 'Pastilha de Freio',
    sku: 'PF-300',
    supplier: 'Bosch',
    seller: 'Carlos',
    requestDate: '2023-07-10',
    value: 120.0,
    status: 'Nota Fiscal em Análise',
    returnInvoiceUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    slaDays: 65,
    category: 'Outros',
  },
  {
    id: 'DEV-1004',
    type: 'Devolução Comum',
    customer: 'Mecânica Express',
    product: 'Correia Dentada',
    sku: 'CD-400',
    supplier: 'Gates',
    seller: 'Ana',
    requestDate: '2023-10-05',
    value: 85.0,
    status: 'Crédito Liberado',
    slaDays: 5,
    category: 'Outros',
  },
  {
    id: 'GRT-1005',
    type: 'Garantia',
    customer: 'Auto Peças Silva',
    product: "Bomba d'água",
    sku: 'BD-500',
    supplier: 'Urba',
    seller: 'João Pedro',
    requestDate: '2023-08-01',
    value: 320.0,
    status: 'Enviado ao Fornecedor',
    slaDays: 45,
    category: 'Outros',
  },
  {
    id: 'DEV-1006',
    type: 'Devolução Comum',
    customer: 'Oficina do Marcos',
    product: 'Vela de Ignição',
    sku: 'VI-600',
    supplier: 'NGK',
    seller: 'Carlos',
    requestDate: '2023-10-06',
    value: 60.0,
    status: 'NF Recusada',
    slaDays: 1,
    category: 'Outros',
  },
  {
    id: 'GRT-1007',
    type: 'Garantia',
    customer: 'Centro Automotivo RJ',
    product: 'Amortecedor Traseiro',
    sku: 'AM-201',
    supplier: 'Monroe',
    seller: 'Ana',
    requestDate: '2023-06-20',
    value: 450.0,
    status: 'Autorizado emissão da nota fiscal',
    slaDays: 72,
    category: 'Amortecedor',
  },
]

export const generateId = () => `PRC-${Math.floor(Math.random() * 10000) + 2000}`
